services:
  DeathNoteAPI:
    container_name: DeathNoteAPI
    build: .
    ports:
        - "8000:8000"
    depends_on:
      DeathNoteAPIdb:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  DeathNoteAPIdb:
    container_name: DeathNoteAPIdb
    image: postgres:16
    expose:
        - ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - death_note_db:/var/lib/postgresql/data
      # - ./database/init:/docker-entrypoint-initdb.d:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  death_note_db:
