services:
  deathnoteapi:
    container_name: deathnoteapi
    build: .
    ports:
        - "8000:8000"
    environment:
      - FIRE_BASE_KEY=${FIRE_BASE_KEY}
      - APY_KEY=${APY_KEY} 
      - AUTH_DOMAIN=${AUTH_DOMAIN}
      - PROJECT_ID=${PROJECT_ID}
      - STORAGE_BUCKET=${STORAGE_BUCKET} 
      - MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
      - APP_ID=${APP_ID}
      - MEASUREMENT_ID=${MEASUREMENT_ID}
    develop:
      watch:
        - action: rebuild
          path: ./app
          target: /DeathNoteFake/app
