[project]
name = "DeathNote"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "firebase-admin>=6.7.0",
    "pydantic-settings>=2.8.1",
    "pyrebase4>=4.8.0",
    "setuptools>=78.1.0",
]
